### ISSUE TITLE
seed_db is not defined by Heroku

### ISSUE THREAD

**Issue by QurQuma** [Parassharmaa/auto-twitter-dm#3]
Hi,
  just launched this app on Heroku. All seems fine with settings but I get this error message:
2018-03-06T10:11:14.850936+00:00 app[api]: - Release v10 created by user francesco@qurquma.it
2018-03-06T10:11:17.030451+00:00 heroku[clock.1]: - State changed from crashed to starting
2018-03-06T10:11:20.617536+00:00 heroku[clock.1]: - Starting process with command `python clock.py`
2018-03-06T10:11:21.242790+00:00 heroku[clock.1]: - State changed from starting to up
2018-03-06T10:11:22.467661+00:00 app[clock.1]: - Traceback (most recent call last):
2018-03-06T10:11:22.467685+00:00 app[clock.1]: -   File "clock.py", line 27, in <module>
2018-03-06T10:11:22.467861+00:00 app[clock.1]: -     seed_db(tw_username)
2018-03-06T10:11:22.467868+00:00 app[clock.1]: - NameError: name 'seed_db' is not defined
2018-03-06T10:11:23.009497+00:00 heroku[clock.1]: - Process exited with status 1
2018-03-06T10:11:23.194709+00:00 heroku[clock.1]: - State changed from up to crashed
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
What can be the cause?
Thanks,
Francesco

**Comment by IgorVaryvoda** [comment]
Add this line to  the top of clock.py
`from twautomate import seed_db`

**Comment by QurQuma** [comment]
Thanks, it starts now but immediately crashes.

`:44.608467+00:00 heroku[clock.1]: Process exited with status 1
2018-03-16T12:52:53.000000+00:00 app[api]: Build started by user francesco@qurquma.it
2018-03-16T12:53:08.955756+00:00 app[api]: Deploy 96bc686a by user francesco@qurquma.it
2018-03-16T12:53:08.955756+00:00 app[api]: Release v14 created by user francesco@qurquma.it
2018-03-16T12:52:53.000000+00:00 app[api]: Build succeeded
2018-03-16T12:53:09.934761+00:00 heroku[clock.1]: State changed from crashed to starting
2018-03-16T12:53:13.119821+00:00 heroku[clock.1]: Starting process with command `python clock.py`
2018-03-16T12:53:13.862736+00:00 heroku[clock.1]: State changed from starting to up
2018-03-16T12:53:15.599827+00:00 app[clock.1]: 0
2018-03-16T12:53:15.794742+00:00 app[clock.1]: 8027
2018-03-16T12:53:15.822744+00:00 app[clock.1]: Traceback (most recent call last):
2018-03-16T12:53:15.822751+00:00 app[clock.1]:   File "clock.py", line 28, in <module>
2018-03-16T12:53:15.822896+00:00 app[clock.1]:     seed_db(tw_username)
2018-03-16T12:53:15.822899+00:00 app[clock.1]:   File "/app/twautomate.py", line 31, in seed_db
2018-03-16T12:53:15.823000+00:00 app[clock.1]:     save_followers(username, n)
2018-03-16T12:53:15.823003+00:00 app[clock.1]:   File "/app/twautomate.py", line 50, in save_followers
2018-03-16T12:53:15.823103+00:00 app[clock.1]:     upsert=True)
2018-03-16T12:53:15.823106+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/collection.py", line 976, in update_one
2018-03-16T12:53:15.823490+00:00 app[clock.1]:     session=session),
2018-03-16T12:53:15.823493+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/collection.py", line 836, in _update_retryable
2018-03-16T12:53:15.823815+00:00 app[clock.1]:     _update, session)
2018-03-16T12:53:15.823818+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1102, in _retryable_write
2018-03-16T12:53:15.824265+00:00 app[clock.1]:     return self._retry_with_session(retryable, func, s, None)
2018-03-16T12:53:15.824269+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1069, in _retry_with_session
2018-03-16T12:53:15.824642+00:00 app[clock.1]:     with self._get_socket(server) as sock_info:
2018-03-16T12:53:15.824644+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/contextlib.py", line 81, in __enter__
2018-03-16T12:53:15.824749+00:00 app[clock.1]:     return next(self.gen)
2018-03-16T12:53:15.824751+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/mongo_client.py", line 947, in _get_socket
2018-03-16T12:53:15.825226+00:00 app
[clock.1]:     with server.get_socket(self.__all_credentials) as sock_info:
2018-03-16T12:53:15.825227+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/contextlib.py", line 81, in __enter__
2018-03-16T12:53:15.825334+00:00 app[clock.1]:     return next(self.gen)
2018-03-16T12:53:15.825337+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/server.py", line 138, in get_socket
2018-03-16T12:53:15.825463+00:00 app[clock.1]:     with self.pool.get_socket(all_credentials, checkout) as sock_info:
2018-03-16T12:53:15.825466+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/contextlib.py", line 81, in __enter__
2018-03-16T12:53:15.825568+00:00 app[clock.1]:     return next(self.gen)
2018-03-16T12:53:15.825571+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/pool.py", line 920, in get_socket
2018-03-16T12:53:15.825978+00:00 app[clock.1]:     sock_info.check_auth(all_credentials)
2018-03-16T12:53:15.825982+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/pool.py", line 609, in check_auth
2018-03-16T12:53:15.826350+00:00 app[clock.1]:     auth.authenticate(credentials, self)
2018-03-16T12:53:15.826354+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/auth.py", line 486, in authenticate
2018-03-16T12:53:15.826676+00:00 app[clock.1]:     auth_func(credentials, sock_info)
2018-03-16T12:53:15.826693+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/auth.py", line 466, in _authenticate_default
2018-03-16T12:53:15.826926+00:00 app[clock.1]:     return _authenticate_scram_sha1(credentials, sock_info)
2018-03-16T12:53:15.826932+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/auth.py", line 209, in _authenticate_scram_sha1
2018-03-16T12:53:15.827060+00:00 app[clock.1]:     res = sock_info.command(source, cmd)
2018-03-16T12:53:15.827063+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3
.6/site-pack
ages/pymongo/pool.py", line 517, in command
2018-03-16T12:53:15.827288+00:00 app[clock.1]:     collation=collation)
2018-03-16T12:53:15.827291+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/network.py", line 125, in command
2018-03-16T12:53:15.827409+00:00 app[clock.1]:     parse_write_concern_error=parse_write_concern_error)
2018-03-16T12:53:15.827412+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/helpers.py", line 145, in _check_command_response
2018-03-16T12:53:15.827534+00:00 app[clock.1]:     raise OperationFailure(msg % errmsg, code, response)
2018-03-16T12:53:15.827552+00:00 app[clock.1]: pymongo.errors.OperationFailure: Authentication failed.
2018-03-16T12:53:16.027252+00:00 heroku[clock.1]: Process exited with status 1
2018-03-16T12:53:16.328838+00:00 heroku[clock.1]: State changed from up to crashed
2018-03-16T12:53:16.330744+00:00 heroku[clock.1]: State changed from crashed to starting
2018-03-16T12:53:19.704609+00:00 heroku[clock.1]: Starting process with command `python clock.py`
2018-03-16T12:53:20.611655+00:00 heroku[clock.1]: State changed from starting to up
2018-03-16T12:53:22.403961+00:00 app[clock.1]: 0
2018-03-16T12:53:22.625362+00:00 app[clock.1]: 8027
2018-03-16T12:53:22.654494+00:00 app[clock.1]: Traceback (most recent call last):
2018-03-16T12:53:22.657148+00:00 app[clock.1]:   File "clock.py", line 28, in <module>
2018-03-16T12:53:22.657419+00:00 app[clock.1]:     seed_db(tw_username)
2018-03-16T12:53:22.669909+00:00 app[clock.1]:   File "/app/twautomate.py", line 31, in seed_db
2018-03-16T12:53:22.672477+00:00 app[clock.1]:     save_followers(username, n)
2018-03-16T12:53:22.672517+00:00 app[clock.1]:   File "/app/twautomate.py", line 50, in save_followers
2018-03-16T12:53:22.672715+00:00 app[clock.1]:     upsert=True)
2018-03-16T12:53:22.672777+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/collection.py", line 976, in update_one
2018-03-16T12:53:22.673529+00:00 app[clock.1]:     session=session),
2018-03-16T12:53:22.673685+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/collection.py", line 836, in _update_retryable
2018-03-16T12:53:22.674341+00:00 app[clock.1]:     _update, session)
2018-03-16T12:53:22.674389+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1102, in _retryable_write
2018-03-16T12:53:22.675255+00:00 app[clock.1]:     return self._retry_with_session(retryable, func, s, None)
2018-03-16T12:53:22.675321+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1069, in _retry_with_session
2018-03-16T12:53:22.676106+00:00 app[clock.1]:     with self._get_socket(server) as sock_info:
2018-03-16T12:53:22.676155+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/contextlib.py", line 81, in __enter__
2018-03-16T12:53:22.676357+00:00 app[clock.1]:     return next(self.gen)
2018-03-16T12:53:22.676396+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/mongo_client.py", line 947, in _get_socket
2018-03-16T12:53:22.677152+00:00 app[clock.1]:     with server.get_socket(self.__all_credentials) as sock_info:
2018-03-16T12:53:22.67807
2+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/contextlib.py", line 81, in __enter__
2018-03-16T12:53:22.678284+00:00 app[clock.1]:     return next(self.gen)
2018-03-16T12:53:22.678323+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/server.py", line 138, in get_socket
2018-03-16T12:53:22.678565+00:00 app[clock.1]:     with self.pool.get_socket(all_credentials, checkout) as sock_info:
2018-03-16T12:53:22.678604+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/contextlib.py", line 81, in __enter__
2018-03-16T12:53:22.678808+00:00 app[clock.1]:     return next(self.gen)
2018-03-16T12:53:22.678847+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/pool.py", line 920, in get_socket
2018-03-16T12:53:22.679555+00:00 app[clock.1]:     sock_info.check_auth(all_credentials)
2018-03-16T12:53:22.679594+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/pool.py", line 609, in check_auth
2018-03-16T12:53:22.680089+00:00 app[clock.1]:     auth.authenticate(credentials, self)
2018-03-16T12:53:22.680127+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/auth.py", line 486, in authenticate
2018-03-16T12:53:22.680570+00:00 app[clock.1]:     auth_func(credentials, sock_info)
2018-03-16T12:53:22.680605+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/auth.py", line 466, in _authenticate_default
2018-03-16T12:53:22.681037+00:00 app[clock.1]:     return _authenticate_scram_sha1(credentials, sock_info)
2018-03-16T12:53:22.683113+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/auth.py", line 209, in _authenticate_scram_sha1
2018-03-16T12:53:22.683413+00:00 app[clock.1]:     res = sock_info.command(source, cmd)
2018-03-16T12:53:22.683462+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/pool.py", line 517, in command
2018-03-16T12:53:22.683930+00:00 app[clock.1]
:     collat
ion=collation)
2018-03-16T12:53:22.683969+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/network.py", line 125, in command
2018-03-16T12:53:22.684208+00:00 app[clock.1]:     parse_write_concern_error=parse_write_concern_error)
2018-03-16T12:53:22.684245+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/helpers.py", line 145, in _check_command_response
2018-03-16T12:53:22.684811+00:00 app[clock.1]:     raise OperationFailure(msg % errmsg, code, response)
2018-03-16T12:53:22.684813+00:00 app[clock.1]: pymongo.errors.OperationFailure: Authentication failed.`

**Comment by IgorVaryvoda** [comment]
Haha, I literally had the same experience as you :) Go to https://mlab.com/databases/YourDbName#users and create a user. Than use that info for the development variable 

`DB_AUTOMATE  => mongodb://<dbuser>:<dbpassword>@ds111078.mlab.com:11078/dbname`

**Comment by QurQuma** [comment]
I made a mistake adding username value to DB_AUTOMATE, you're right.
Now app is up and running. 
Waiting for new follews to come ;)
Thanks,
Francesco

**Comment by IgorVaryvoda** [comment]
I've set this script up today, it seems to be working fine. Cheers!

**Comment by QurQuma** [comment]
It works perfectly now.
Thanks!
